In [2]:
import numpy as np

a = np.array([[1,2,3], [5,6,7], [9,10,11], [13,14,15]])
a

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [6]:
b = a.T * -1
print(b)
print(f"The matrix b dimensions is: {b.shape}")
print(f"b dimensions is equal to a dimensions: {b.shape == a.shape}")

[[ -1  -5  -9 -13]
 [ -2  -6 -10 -14]
 [ -3  -7 -11 -15]]
The matrix b dimensions is: (3, 4)
b dimensions is equal to a dimensions: False
